function sb = get_sbmatrix(numsignal,numblock,signal,sbind)

vec = sbind{numsignal,numblock};
sb = zeros(length(vec),6);
for k1 = 1 : length(vec)
    sb(k1,:) = [ signal(numsignal).block(numblock).structbook(vec(k1)).coef ...
                 signal(numsignal).block(numblock).structbook(vec(k1)).rho ...
                 signal(numsignal).block(numblock).structbook(vec(k1)).xi ...
                 signal(numsignal).block(numblock).structbook(vec(k1)).phase ...
                 signal(numsignal).block(numblock).structbook(vec(k1)).ti ...
                 signal(numsignal).block(numblock).structbook(vec(k1)).tf];
end


